### ISSUE TITLE
Menu Icons

### ISSUE THREAD

**Issue by l-zeuch** [botlabs-gg/yagpdb-docs-v2#35]
Transferred from #33 ("general: add menu icons for pages") by @SoggySaussages:

> For your consideration: Icons in menu options.
> ### Pros
> 
> 1. Break up the text wall
> 
> 2. Familiarity
> 
> 3. Easy navigation to the section you're looking for when coming from the control panel
> 
> 
> ### Cons
> 
> 1. More visually busy
> 
> 2. There are more docs pages than there are pages on YAG, users may be confused why there's a page with an icon in docs' menu bar but not able to find the page on control panel
> 
> 3. Easier for new users to mistake docs for control panel
> 
> 
> Please take a look and share thoughts (or deny instantly, whichever works :)) https://yagdocsv2.vedamaharaj.ca/yagpdb-docs-v2/

Do consider that we're currently in the midst of migrating the theme from Relearn to Hugo. That means a realistic consensus can only be formed once said migration is done, because something that might not work with Relearn might work with Doks, and vice versa.

That said, either chip in your two cents, or vote with reactions to not flood this thread with noise.

**Comment by jo3-l** [comment]
Closing for now given the Doks migration, but feel free to reopen if still relevant.

**Comment by l-zeuch** [comment]
@jo3-l I opened this *because* we were migrating to Doks. Point of this issue is to discuss whether we want to use icons as proposed in #33, which I just closed as it didn't make sense to merge during the migration.

**Comment by jo3-l** [comment]
Thanks for the clarification; I misunderstood the context of the original issue. I was under the impression that Relearn supported menu icons natively whereas Doks does not, but this point is not applicable: #33 uses a bit of a hack to add the icon which should work fine with Doks as well.

**Comment by SoggySaussages** [comment]
> Thanks for the clarification; I misunderstood the context of the original issue. I was under the impression that Relearn supported menu icons natively whereas Doks does not, but this point is not applicable: #33 uses a bit of a hack to add the icon which should work fine with Doks as well.

Noting that the hacky method I used was as documented on Relearn docs, I can’t be sure if the same thing would work on Doks.

**Comment by l-zeuch** [comment]
To chip in my two cents:

> More visually busy

100% agreed. Personally I prefer a rather plain documentation, focusing on text rather than visual features such as icons.

> There are more docs pages than there are pages on YAG, users may be confused why there's a page with an icon in docs' menu bar but not able to find the page on control panel

This might be an actual blocker for this. We took great care to name the main headers the same as they are on the control panel for ease of navigation. Introducing additional icons for pages that are *not* on the control panel but *are* in the documentation doesn't seem like a good idea to me.

> Easier for new users to mistake docs for control panel

I don't think this is much of an issue, no matter how new to YAGPDB a user might me. The docs are visually very distinct from the control panel (which they should be). The mere presence of plain text rather than knobs and buttons should further indicate that this is the wrong place for configuration.

> Break up the text wall

I don't really see this, to be fair. If anything, they might even add to a "text wall", making it worse for navigation.

> Easy navigation to the section you're looking for when coming from the control panel

See my comment about us making sure we use the same names for headers as on the control panel.

All in all I'm leaning towards *not* adding icons, but I'm happy to hear your thoughts on this.

**Comment by l-zeuch** [comment]
Internal discussion has concluded that we don't like this.
